//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahteVeri.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SahteVeri.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deneme Mahallesi Deneme Caddesi No:1.
        /// </summary>
        internal static string adresler {
            get {
                return ResourceManager.GetString("adresler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berke
        ///Ahmetcan
        ///Jale
        ///Ali
        ///Mahmut
        ///Mansur Kürşad
        ///Gamze
        ///Miraç
        ///Yücel
        ///Kubilay
        ///Hayati
        ///Bedriye Müge
        ///Birsen
        ///Serdal
        ///Bünyamin
        ///Özgür
        ///Ferdi
        ///Reyhan
        ///İlhan
        ///Gülşah
        ///Nalan
        ///Semih
        ///Ergün
        ///Fatih
        ///Şenay
        ///Serkan
        ///Emre
        ///Bahattin
        ///Irazca
        ///Hatice
        ///Barış
        ///Rezan
        ///Fatih
        ///Fuat
        ///Gökhan
        ///Orhan
        ///Mehmet
        ///Evren
        ///Oktay
        ///Harun
        ///Yavuz
        ///Pınar
        ///Mehmet
        ///Umut
        ///Mesude
        ///Hüseyin Cahit
        ///Haşim Onur
        ///Eyyup Sabri
        ///Mustafa
        ///Mustafa
        ///Ufuk
        ///Ahmet Ali
        ///Mediha
        ///Hasan
        ///Kamil
        ///Nebi
        ///Özcan
        ///Nagihan
        ///Ceren
        ///Serkan
        ///Hasan
        ///Yusuf Kenan
        ///Çetin
        ///Tar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isimler {
            get {
                return ResourceManager.GetString("isimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acentacı
        ///Acil durum yönetmeni
        ///Adli tabip
        ///Ağ yöneticisi
        ///Aşçı
        ///Aşçıbaşı
        ///Aile hekimi
        ///Aktar
        ///Aktör
        ///Analist
        ///Anestezi uzmanı
        ///Animatör
        ///Apartman yöneticisi
        ///Araba satıcısı
        ///Araba yıkayıcısı
        ///Avukat
        ///Bilimadamı
        ///Bisikletçi
        ///Biyografi yazarı
        ///Biyolog
        ///Bobinajcı
        ///Bombacı
        ///Bomba imhacı
        ///Borsacı
        ///Borucu
        ///Botanikçi
        ///Boyacı
        ///Bozacı
        ///Böcekbilimci
        ///Börekçi
        ///Bulaşıkçı
        ///Buldozer operatörü
        ///Bütçe uzmanı
        ///Büyükelçi
        ///Besicilik
        ///Bebek Bakıcısı
        ///Bilgi İşlemci
        ///Camcı
        ///Cerrah
        ///Çevirmen
        ///Dalgıç
        ///Danışman
        ///Ebe
        ///Eczacı
        ///Eczac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meslekler {
            get {
                return ResourceManager.GetString("meslekler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adana 
        ///Adıyaman
        ///Afyonkarahisar
        ///Ağrı
        ///Aksaray
        ///Amasya
        ///Ankara
        ///Antalya
        ///Ardahan
        ///Artvin
        ///Aydın
        ///Balıkesir
        ///Bartın
        ///Batman
        ///Bayburt
        ///Bilecik
        ///Bingöl
        ///Bitlis
        ///Bolu
        ///Burdur
        ///Bursa
        ///Çanakkale
        ///Çankırı
        ///Çorum
        ///Denizli
        ///Diyarbakır
        ///Düzce
        ///Edirne 
        ///Elazığ
        ///Erzincan
        ///Erzurum
        ///Eskişehir
        ///Gaziantep
        ///Giresun
        ///Gümüşhane
        ///Hakkari
        ///Hatay
        ///Iğdır
        ///Isparta
        ///İstanbul
        ///İzmir
        ///Kahramanmaraş
        ///Karabük
        ///Karaman
        ///Kars
        ///Kastamonu
        ///Kayseri
        ///Kırıkkale
        ///Kırklareli
        ///Kırşehir
        ///Kilis
        ///Kocaeli
        ///Konya
        ///Kütahya
        ///Malatya
        ///Manisa
        ///Mardin
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sehirler {
            get {
                return ResourceManager.GetString("sehirler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deneme Şirketi
        ///.
        /// </summary>
        internal static string sirketler {
            get {
                return ResourceManager.GetString("sirketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurnaz
        ///Şen
        ///Kandemir
        ///Çevik
        ///Erkuran
        ///Tüten
        ///Öztürk
        ///Yüzbaşıoğlu
        ///Vural
        ///Yücel
        ///Sönmez
        ///Ertekin
        ///Dede
        ///Uyanık
        ///Aslan
        ///Akbulut
        ///Orhon
        ///Uz
        ///Yavuz
        ///Erdem
        ///Kulaç
        ///Kaya
        ///Selvi
        ///Akpınar
        ///Abacıoğlu
        ///Çay
        ///Işık
        ///Özer
        ///Özdemir
        ///Öztürk
        ///Tahtacı
        ///Büyükcam
        ///Kulaksız
        ///Aksel
        ///Eroğlu
        ///Karakum
        ///Dal
        ///Öcal
        ///Ayhan
        ///Yiğit
        ///Yarbil
        ///Canacankatan
        ///Gümüşay
        ///Murt
        ///Halhallı
        ///Uluöz
        ///Şeyhanlı
        ///Çalışkantürk
        ///Yılmaz
        ///Saraçoğlu
        ///Sezer
        ///Doğan
        ///Demir
        ///Kayayurt
        ///Sürüm
        ///Yavaşi
        ///Turgut
        ///Şen Tanrıkulu
        ///Barbaros
        ///Aldinç
        ///Tekin
        ///Gülşan
        ///Küfecile [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string soyisimler {
            get {
                return ResourceManager.GetString("soyisimler", resourceCulture);
            }
        }
    }
}
